services:
  db_cicd:
    image: postgres
    container_name: db_cicd
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  node:
    container_name: studentsCICD
    build: .
    ports:
      - 5009:5000
    depends_on:
      - db_cicd
    env_file:
      - .env

volumes:
  pg: